name: "Ci"
on:
  push:
    branches: ['main']
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: Heihokon
          repo: test-demo
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: pages.yml

